version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    platform: linux/amd64 # Specify platform for the app service
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/elsa-db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elsa-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: asdfg;lkjh1234
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
