version: "3.8"

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elsa-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: asdfg;lkjh1234
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  auth-service:
    build:
      context: ./
      dockerfile: dockerfile.auth
    ports:
      - "3001:3001"
    depends_on:
      - event-bus
      - db
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  quiz-service:
    build:
      context: ./
      dockerfile: dockerfile.quiz
    ports:
      - "3002:3002"
    depends_on:
      - event-bus
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  proxy-server:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - quiz-service
    networks:
      - app-network

  event-bus:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
